# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from zoom_meeting_python_sdk.paths.archive_files_statistics.get import GetStatistics
from zoom_meeting_python_sdk.paths.past_meetings_meeting_uuid_archive_files.delete import MeetingFilesDelete
from zoom_meeting_python_sdk.paths.archive_files.get import MeetingFilesList
from zoom_meeting_python_sdk.paths.past_meetings_meeting_uuid_archive_files.get import MeetingFilesList0
from zoom_meeting_python_sdk.paths.archive_files_file_id.patch import UpdateAutoDeleteStatus
from zoom_meeting_python_sdk.apis.tags.archiving_api_raw import ArchivingApiRaw


class ArchivingApi(
    GetStatistics,
    MeetingFilesDelete,
    MeetingFilesList,
    MeetingFilesList0,
    UpdateAutoDeleteStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ArchivingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ArchivingApiRaw(api_client)
