# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from zoom_meeting_python_sdk.paths.devices_zpa_assignment.post import AssignDeviceZpaAssignmentRaw
from zoom_meeting_python_sdk.paths.devices_device_id_assignment.patch import ChangeDeviceAssociationRaw
from zoom_meeting_python_sdk.paths.devices.post import CreateNewDeviceRaw
from zoom_meeting_python_sdk.paths.devices_device_id.get import GetDetailRaw
from zoom_meeting_python_sdk.paths.devices_zpa_zdm_groups_zdm_group_id_versions.get import GetZpaVersionInfoRaw
from zoom_meeting_python_sdk.paths.devices.get import ListRaw
from zoom_meeting_python_sdk.paths.devices_groups.get import ListZdmGroupInfoRaw
from zoom_meeting_python_sdk.paths.devices_device_id.delete import RemoveDeviceZmdRaw
from zoom_meeting_python_sdk.paths.devices_zpa_vendors_vendor_mac_addresses_mac_address.delete import RemoveZpaDeviceByVendorAndMacAddressRaw
from zoom_meeting_python_sdk.paths.devices_device_id.patch import UpdateDeviceNameRaw
from zoom_meeting_python_sdk.paths.devices_zpa_upgrade.post import UpgradeZpaOsAppRaw


class DevicesApiRaw(
    AssignDeviceZpaAssignmentRaw,
    ChangeDeviceAssociationRaw,
    CreateNewDeviceRaw,
    GetDetailRaw,
    GetZpaVersionInfoRaw,
    ListRaw,
    ListZdmGroupInfoRaw,
    RemoveDeviceZmdRaw,
    RemoveZpaDeviceByVendorAndMacAddressRaw,
    UpdateDeviceNameRaw,
    UpgradeZpaOsAppRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
