# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from zoom_meeting_python_sdk.paths.h323_devices.post import CreateDeviceRaw
from zoom_meeting_python_sdk.paths.h323_devices_device_id.delete import DeleteDeviceRaw
from zoom_meeting_python_sdk.paths.h323_devices.get import ListDevicesRaw
from zoom_meeting_python_sdk.paths.h323_devices_device_id.patch import UpdateDeviceInfoRaw


class H323DevicesApiRaw(
    CreateDeviceRaw,
    DeleteDeviceRaw,
    ListDevicesRaw,
    UpdateDeviceInfoRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
