# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from zoom_meeting_python_sdk.paths.users_user_id_pac.get import ListAccounts
from zoom_meeting_python_sdk.apis.tags.pac_api_raw import PACApiRaw


class PACApi(
    ListAccounts,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PACApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PACApiRaw(api_client)
