# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from zoom_meeting_python_sdk.paths.tracking_fields.post import CreateFieldRaw
from zoom_meeting_python_sdk.paths.tracking_fields_field_id.delete import DeleteFieldRaw
from zoom_meeting_python_sdk.paths.tracking_fields_field_id.get import GetRaw
from zoom_meeting_python_sdk.paths.tracking_fields.get import ListRaw
from zoom_meeting_python_sdk.paths.tracking_fields_field_id.patch import UpdateRaw


class TrackingFieldApiRaw(
    CreateFieldRaw,
    DeleteFieldRaw,
    GetRaw,
    ListRaw,
    UpdateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
