# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from zoom_meeting_python_sdk.pydantic.webinars_get_details_response_occurrences import WebinarsGetDetailsResponseOccurrences
from zoom_meeting_python_sdk.pydantic.webinars_get_details_response_recurrence import WebinarsGetDetailsResponseRecurrence
from zoom_meeting_python_sdk.pydantic.webinars_get_details_response_settings import WebinarsGetDetailsResponseSettings
from zoom_meeting_python_sdk.pydantic.webinars_get_details_response_tracking_fields import WebinarsGetDetailsResponseTrackingFields

class WebinarsGetDetailsResponse(BaseModel):
    # Email address of the meeting host.
    host_email: typing.Optional[str] = Field(None, alias='host_email')

    # ID of the user set as host of webinar.
    host_id: typing.Optional[str] = Field(None, alias='host_id')

    # Webinar ID in **long** format(represented as int64 data type in JSON), also known as the webinar number.
    id: typing.Optional[int] = Field(None, alias='id')

    # Unique webinar ID. Each webinar instance will generate its own webinar UUID. After a webinar ends, a new UUID is generated for the next instance of the webinar. Retrieve a list of UUIDs from past webinar instances using the [**List past webinar instances**](https://developers.zoom.us) API. [Double encode](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#meeting-id-and-uuid) your UUID when using it for API calls if the UUID begins with a `/` or contains `//` in it.  
    uuid: typing.Optional[str] = Field(None, alias='uuid')

    # Webinar agenda.
    agenda: typing.Optional[str] = Field(None, alias='agenda')

    # Create time.
    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    # Webinar duration.
    duration: typing.Optional[int] = Field(None, alias='duration')

    # URL to join the webinar. Only share this URL with the users who should be invited to the webinar.
    join_url: typing.Optional[str] = Field(None, alias='join_url')

    occurrences: typing.Optional[WebinarsGetDetailsResponseOccurrences] = Field(None, alias='occurrences')

    # Webinar passcode.   If **Require a passcode when scheduling new meetings** setting has been **enabled** **and** [locked](https://support.zoom.us/hc/en-us/articles/115005269866-Using-Tiered-Settings#locked) for the user, the passcode field will be autogenerated for the Webinar in the response even if it is not provided in the API request.           **Note:** If the account owner or the admin has configured [minimum passcode requirement settings](https://support.zoom.us/hc/en-us/articles/360033559832-Meeting-and-webinar-passwords#h_a427384b-e383-4f80-864d-794bf0a37604), the passcode value provided here must meet those requirements.         If the requirements are enabled, you can view those requirements by calling either the [**Get user settings**](https://developers.zoom.us) API or the [**Get account settings**](https://developers.zoom.us) API.
    password: typing.Optional[str] = Field(None, alias='password')

    # Encrypted passcode for third party endpoints (H323/SIP).
    encrypted_passcode: typing.Optional[str] = Field(None, alias='encrypted_passcode')

    # H.323/SIP room system passcode.
    h323_passcode: typing.Optional[str] = Field(None, alias='h323_passcode')

    recurrence: typing.Optional[WebinarsGetDetailsResponseRecurrence] = Field(None, alias='recurrence')

    settings: typing.Optional[WebinarsGetDetailsResponseSettings] = Field(None, alias='settings')

    # Webinar start time in GMT/UTC.
    start_time: typing.Optional[datetime] = Field(None, alias='start_time')

    #     The `start_url` of a webinar is a URL using which a host or an alternative host can start the webinar. This URL should only be used by the host of the meeting and should not be shared with anyone other than the host of the webinar.   The expiration time for the `start_url` field listed in the response of the [**Create a webinar**](https://developers.zoom.us) API is two hours for all regular users.    For users created using the `custCreate` option via the [**Create users**](https://developers.zoom.us) API, the expiration time of the `start_url` field is 90 days.   For security reasons, to retrieve the latest value for the `start_url` field programmatically (after expiry), you must call the [**Get a webinar**](https://developers.zoom.us) API and refer to the value of the `start_url` field in the response.    
    start_url: typing.Optional[str] = Field(None, alias='start_url')

    # Time zone to format `start_time`.
    timezone: typing.Optional[str] = Field(None, alias='timezone')

    # Webinar topic.
    topic: typing.Optional[str] = Field(None, alias='topic')

    tracking_fields: typing.Optional[WebinarsGetDetailsResponseTrackingFields] = Field(None, alias='tracking_fields')

    # Webinar types.   `5` - Webinar.    `6` - Recurring webinar with no fixed time.    `9` - Recurring webinar with a fixed time.
    type: typing.Optional[Literal[5, 6, 9]] = Field(None, alias='type')

    # Whether the webinar is `simulive`.
    is_simulive: typing.Optional[bool] = Field(None, alias='is_simulive')

    # The previously recorded file's ID for `simulive`.
    record_file_id: typing.Optional[str] = Field(None, alias='record_file_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
