# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from zoom_meeting_python_sdk import schemas  # noqa: F401


class MeetingsGetDetailsResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Meeting object.
    """


    class MetaOapg:
        
        class properties:
            assistant_id = schemas.StrSchema
            host_email = schemas.StrSchema
            host_id = schemas.StrSchema
            id = schemas.Int64Schema
            uuid = schemas.StrSchema
            
            
            class agenda(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 2000
            created_at = schemas.DateTimeSchema
            duration = schemas.IntSchema
            encrypted_password = schemas.StrSchema
            h323_password = schemas.StrSchema
            join_url = schemas.StrSchema
            chat_join_url = schemas.StrSchema
        
            @staticmethod
            def occurrences() -> typing.Type['MeetingsGetDetailsResponseOccurrences']:
                return MeetingsGetDetailsResponseOccurrences
            
            
            class password(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
            pmi = schemas.StrSchema
            pre_schedule = schemas.BoolSchema
        
            @staticmethod
            def recurrence() -> typing.Type['MeetingsGetDetailsResponseRecurrence']:
                return MeetingsGetDetailsResponseRecurrence
        
            @staticmethod
            def settings() -> typing.Type['MeetingsGetDetailsResponseSettings']:
                return MeetingsGetDetailsResponseSettings
            start_time = schemas.DateTimeSchema
            start_url = schemas.StrSchema
            
            
            class status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "waiting": "WAITING",
                        "started": "STARTED",
                    }
                
                @schemas.classproperty
                def WAITING(cls):
                    return cls("waiting")
                
                @schemas.classproperty
                def STARTED(cls):
                    return cls("started")
            timezone = schemas.StrSchema
            topic = schemas.StrSchema
        
            @staticmethod
            def tracking_fields() -> typing.Type['MeetingsGetDetailsResponseTrackingFields']:
                return MeetingsGetDetailsResponseTrackingFields
            
            
            class type(
                schemas.EnumBase,
                schemas.IntSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        1: "POSITIVE_1",
                        2: "POSITIVE_2",
                        3: "POSITIVE_3",
                        8: "POSITIVE_8",
                    }
                
                @schemas.classproperty
                def POSITIVE_1(cls):
                    return cls(1)
                
                @schemas.classproperty
                def POSITIVE_2(cls):
                    return cls(2)
                
                @schemas.classproperty
                def POSITIVE_3(cls):
                    return cls(3)
                
                @schemas.classproperty
                def POSITIVE_8(cls):
                    return cls(8)
            __annotations__ = {
                "assistant_id": assistant_id,
                "host_email": host_email,
                "host_id": host_id,
                "id": id,
                "uuid": uuid,
                "agenda": agenda,
                "created_at": created_at,
                "duration": duration,
                "encrypted_password": encrypted_password,
                "h323_password": h323_password,
                "join_url": join_url,
                "chat_join_url": chat_join_url,
                "occurrences": occurrences,
                "password": password,
                "pmi": pmi,
                "pre_schedule": pre_schedule,
                "recurrence": recurrence,
                "settings": settings,
                "start_time": start_time,
                "start_url": start_url,
                "status": status,
                "timezone": timezone,
                "topic": topic,
                "tracking_fields": tracking_fields,
                "type": type,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assistant_id"]) -> MetaOapg.properties.assistant_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host_email"]) -> MetaOapg.properties.host_email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host_id"]) -> MetaOapg.properties.host_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uuid"]) -> MetaOapg.properties.uuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["agenda"]) -> MetaOapg.properties.agenda: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["duration"]) -> MetaOapg.properties.duration: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["encrypted_password"]) -> MetaOapg.properties.encrypted_password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["h323_password"]) -> MetaOapg.properties.h323_password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["join_url"]) -> MetaOapg.properties.join_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chat_join_url"]) -> MetaOapg.properties.chat_join_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["occurrences"]) -> 'MeetingsGetDetailsResponseOccurrences': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pmi"]) -> MetaOapg.properties.pmi: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pre_schedule"]) -> MetaOapg.properties.pre_schedule: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recurrence"]) -> 'MeetingsGetDetailsResponseRecurrence': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["settings"]) -> 'MeetingsGetDetailsResponseSettings': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_time"]) -> MetaOapg.properties.start_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_url"]) -> MetaOapg.properties.start_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timezone"]) -> MetaOapg.properties.timezone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["topic"]) -> MetaOapg.properties.topic: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tracking_fields"]) -> 'MeetingsGetDetailsResponseTrackingFields': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["assistant_id", "host_email", "host_id", "id", "uuid", "agenda", "created_at", "duration", "encrypted_password", "h323_password", "join_url", "chat_join_url", "occurrences", "password", "pmi", "pre_schedule", "recurrence", "settings", "start_time", "start_url", "status", "timezone", "topic", "tracking_fields", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assistant_id"]) -> typing.Union[MetaOapg.properties.assistant_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host_email"]) -> typing.Union[MetaOapg.properties.host_email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host_id"]) -> typing.Union[MetaOapg.properties.host_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uuid"]) -> typing.Union[MetaOapg.properties.uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["agenda"]) -> typing.Union[MetaOapg.properties.agenda, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["duration"]) -> typing.Union[MetaOapg.properties.duration, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["encrypted_password"]) -> typing.Union[MetaOapg.properties.encrypted_password, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["h323_password"]) -> typing.Union[MetaOapg.properties.h323_password, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["join_url"]) -> typing.Union[MetaOapg.properties.join_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chat_join_url"]) -> typing.Union[MetaOapg.properties.chat_join_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["occurrences"]) -> typing.Union['MeetingsGetDetailsResponseOccurrences', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> typing.Union[MetaOapg.properties.password, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pmi"]) -> typing.Union[MetaOapg.properties.pmi, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pre_schedule"]) -> typing.Union[MetaOapg.properties.pre_schedule, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recurrence"]) -> typing.Union['MeetingsGetDetailsResponseRecurrence', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["settings"]) -> typing.Union['MeetingsGetDetailsResponseSettings', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_time"]) -> typing.Union[MetaOapg.properties.start_time, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_url"]) -> typing.Union[MetaOapg.properties.start_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timezone"]) -> typing.Union[MetaOapg.properties.timezone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["topic"]) -> typing.Union[MetaOapg.properties.topic, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tracking_fields"]) -> typing.Union['MeetingsGetDetailsResponseTrackingFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["assistant_id", "host_email", "host_id", "id", "uuid", "agenda", "created_at", "duration", "encrypted_password", "h323_password", "join_url", "chat_join_url", "occurrences", "password", "pmi", "pre_schedule", "recurrence", "settings", "start_time", "start_url", "status", "timezone", "topic", "tracking_fields", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        assistant_id: typing.Union[MetaOapg.properties.assistant_id, str, schemas.Unset] = schemas.unset,
        host_email: typing.Union[MetaOapg.properties.host_email, str, schemas.Unset] = schemas.unset,
        host_id: typing.Union[MetaOapg.properties.host_id, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        uuid: typing.Union[MetaOapg.properties.uuid, str, schemas.Unset] = schemas.unset,
        agenda: typing.Union[MetaOapg.properties.agenda, str, schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, str, datetime, schemas.Unset] = schemas.unset,
        duration: typing.Union[MetaOapg.properties.duration, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        encrypted_password: typing.Union[MetaOapg.properties.encrypted_password, str, schemas.Unset] = schemas.unset,
        h323_password: typing.Union[MetaOapg.properties.h323_password, str, schemas.Unset] = schemas.unset,
        join_url: typing.Union[MetaOapg.properties.join_url, str, schemas.Unset] = schemas.unset,
        chat_join_url: typing.Union[MetaOapg.properties.chat_join_url, str, schemas.Unset] = schemas.unset,
        occurrences: typing.Union['MeetingsGetDetailsResponseOccurrences', schemas.Unset] = schemas.unset,
        password: typing.Union[MetaOapg.properties.password, str, schemas.Unset] = schemas.unset,
        pmi: typing.Union[MetaOapg.properties.pmi, str, schemas.Unset] = schemas.unset,
        pre_schedule: typing.Union[MetaOapg.properties.pre_schedule, bool, schemas.Unset] = schemas.unset,
        recurrence: typing.Union['MeetingsGetDetailsResponseRecurrence', schemas.Unset] = schemas.unset,
        settings: typing.Union['MeetingsGetDetailsResponseSettings', schemas.Unset] = schemas.unset,
        start_time: typing.Union[MetaOapg.properties.start_time, str, datetime, schemas.Unset] = schemas.unset,
        start_url: typing.Union[MetaOapg.properties.start_url, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        timezone: typing.Union[MetaOapg.properties.timezone, str, schemas.Unset] = schemas.unset,
        topic: typing.Union[MetaOapg.properties.topic, str, schemas.Unset] = schemas.unset,
        tracking_fields: typing.Union['MeetingsGetDetailsResponseTrackingFields', schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MeetingsGetDetailsResponse':
        return super().__new__(
            cls,
            *args,
            assistant_id=assistant_id,
            host_email=host_email,
            host_id=host_id,
            id=id,
            uuid=uuid,
            agenda=agenda,
            created_at=created_at,
            duration=duration,
            encrypted_password=encrypted_password,
            h323_password=h323_password,
            join_url=join_url,
            chat_join_url=chat_join_url,
            occurrences=occurrences,
            password=password,
            pmi=pmi,
            pre_schedule=pre_schedule,
            recurrence=recurrence,
            settings=settings,
            start_time=start_time,
            start_url=start_url,
            status=status,
            timezone=timezone,
            topic=topic,
            tracking_fields=tracking_fields,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )

from zoom_meeting_python_sdk.model.meetings_get_details_response_occurrences import MeetingsGetDetailsResponseOccurrences
from zoom_meeting_python_sdk.model.meetings_get_details_response_recurrence import MeetingsGetDetailsResponseRecurrence
from zoom_meeting_python_sdk.model.meetings_get_details_response_settings import MeetingsGetDetailsResponseSettings
from zoom_meeting_python_sdk.model.meetings_get_details_response_tracking_fields import MeetingsGetDetailsResponseTrackingFields
