# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from zoom_meeting_python_sdk import schemas  # noqa: F401


class MeetingsListPastMeetingInstancesResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    List of Meetings
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def meetings() -> typing.Type['MeetingsListPastMeetingInstancesResponseMeetings']:
                return MeetingsListPastMeetingInstancesResponseMeetings
            __annotations__ = {
                "meetings": meetings,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["meetings"]) -> 'MeetingsListPastMeetingInstancesResponseMeetings': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["meetings", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["meetings"]) -> typing.Union['MeetingsListPastMeetingInstancesResponseMeetings', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["meetings", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        meetings: typing.Union['MeetingsListPastMeetingInstancesResponseMeetings', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MeetingsListPastMeetingInstancesResponse':
        return super().__new__(
            cls,
            *args,
            meetings=meetings,
            _configuration=_configuration,
            **kwargs,
        )

from zoom_meeting_python_sdk.model.meetings_list_past_meeting_instances_response_meetings import MeetingsListPastMeetingInstancesResponseMeetings
