# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from zoom_meeting_python_sdk import schemas  # noqa: F401


class ReportsGetActiveInactiveHostReportsResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            _from = schemas.DateSchema
            next_page_token = schemas.StrSchema
            page_count = schemas.IntSchema
            page_number = schemas.IntSchema
            
            
            class page_size(
                schemas.IntSchema
            ):
            
            
                class MetaOapg:
                    inclusive_maximum = 300
            to = schemas.DateSchema
            total_records = schemas.IntSchema
            total_meeting_minutes = schemas.IntSchema
            total_meetings = schemas.IntSchema
            total_participants = schemas.IntSchema
        
            @staticmethod
            def users() -> typing.Type['ReportsGetActiveInactiveHostReportsResponseUsers']:
                return ReportsGetActiveInactiveHostReportsResponseUsers
            __annotations__ = {
                "from": _from,
                "next_page_token": next_page_token,
                "page_count": page_count,
                "page_number": page_number,
                "page_size": page_size,
                "to": to,
                "total_records": total_records,
                "total_meeting_minutes": total_meeting_minutes,
                "total_meetings": total_meetings,
                "total_participants": total_participants,
                "users": users,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["from"]) -> MetaOapg.properties._from: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["next_page_token"]) -> MetaOapg.properties.next_page_token: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["page_count"]) -> MetaOapg.properties.page_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["page_number"]) -> MetaOapg.properties.page_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["page_size"]) -> MetaOapg.properties.page_size: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["to"]) -> MetaOapg.properties.to: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_records"]) -> MetaOapg.properties.total_records: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_meeting_minutes"]) -> MetaOapg.properties.total_meeting_minutes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_meetings"]) -> MetaOapg.properties.total_meetings: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_participants"]) -> MetaOapg.properties.total_participants: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["users"]) -> 'ReportsGetActiveInactiveHostReportsResponseUsers': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["from", "next_page_token", "page_count", "page_number", "page_size", "to", "total_records", "total_meeting_minutes", "total_meetings", "total_participants", "users", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["from"]) -> typing.Union[MetaOapg.properties._from, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["next_page_token"]) -> typing.Union[MetaOapg.properties.next_page_token, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["page_count"]) -> typing.Union[MetaOapg.properties.page_count, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["page_number"]) -> typing.Union[MetaOapg.properties.page_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["page_size"]) -> typing.Union[MetaOapg.properties.page_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["to"]) -> typing.Union[MetaOapg.properties.to, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_records"]) -> typing.Union[MetaOapg.properties.total_records, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_meeting_minutes"]) -> typing.Union[MetaOapg.properties.total_meeting_minutes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_meetings"]) -> typing.Union[MetaOapg.properties.total_meetings, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_participants"]) -> typing.Union[MetaOapg.properties.total_participants, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["users"]) -> typing.Union['ReportsGetActiveInactiveHostReportsResponseUsers', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["from", "next_page_token", "page_count", "page_number", "page_size", "to", "total_records", "total_meeting_minutes", "total_meetings", "total_participants", "users", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        next_page_token: typing.Union[MetaOapg.properties.next_page_token, str, schemas.Unset] = schemas.unset,
        page_count: typing.Union[MetaOapg.properties.page_count, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        page_number: typing.Union[MetaOapg.properties.page_number, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        page_size: typing.Union[MetaOapg.properties.page_size, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        to: typing.Union[MetaOapg.properties.to, str, date, schemas.Unset] = schemas.unset,
        total_records: typing.Union[MetaOapg.properties.total_records, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        total_meeting_minutes: typing.Union[MetaOapg.properties.total_meeting_minutes, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        total_meetings: typing.Union[MetaOapg.properties.total_meetings, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        total_participants: typing.Union[MetaOapg.properties.total_participants, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        users: typing.Union['ReportsGetActiveInactiveHostReportsResponseUsers', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReportsGetActiveInactiveHostReportsResponse':
        return super().__new__(
            cls,
            *args,
            next_page_token=next_page_token,
            page_count=page_count,
            page_number=page_number,
            page_size=page_size,
            to=to,
            total_records=total_records,
            total_meeting_minutes=total_meeting_minutes,
            total_meetings=total_meetings,
            total_participants=total_participants,
            users=users,
            _configuration=_configuration,
            **kwargs,
        )

from zoom_meeting_python_sdk.model.reports_get_active_inactive_host_reports_response_users import ReportsGetActiveInactiveHostReportsResponseUsers
