# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from zoom_meeting_python_sdk import schemas  # noqa: F401


class ReportsGetWebinarSurveyReportResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            webinar_id = schemas.Int64Schema
            webinar_uuid = schemas.StrSchema
            start_time = schemas.DateTimeSchema
            survey_id = schemas.StrSchema
            survey_name = schemas.StrSchema
        
            @staticmethod
            def survey_answers() -> typing.Type['ReportsGetWebinarSurveyReportResponseSurveyAnswers']:
                return ReportsGetWebinarSurveyReportResponseSurveyAnswers
            __annotations__ = {
                "webinar_id": webinar_id,
                "webinar_uuid": webinar_uuid,
                "start_time": start_time,
                "survey_id": survey_id,
                "survey_name": survey_name,
                "survey_answers": survey_answers,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["webinar_id"]) -> MetaOapg.properties.webinar_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["webinar_uuid"]) -> MetaOapg.properties.webinar_uuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_time"]) -> MetaOapg.properties.start_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["survey_id"]) -> MetaOapg.properties.survey_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["survey_name"]) -> MetaOapg.properties.survey_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["survey_answers"]) -> 'ReportsGetWebinarSurveyReportResponseSurveyAnswers': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["webinar_id", "webinar_uuid", "start_time", "survey_id", "survey_name", "survey_answers", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["webinar_id"]) -> typing.Union[MetaOapg.properties.webinar_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["webinar_uuid"]) -> typing.Union[MetaOapg.properties.webinar_uuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_time"]) -> typing.Union[MetaOapg.properties.start_time, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["survey_id"]) -> typing.Union[MetaOapg.properties.survey_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["survey_name"]) -> typing.Union[MetaOapg.properties.survey_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["survey_answers"]) -> typing.Union['ReportsGetWebinarSurveyReportResponseSurveyAnswers', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["webinar_id", "webinar_uuid", "start_time", "survey_id", "survey_name", "survey_answers", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        webinar_id: typing.Union[MetaOapg.properties.webinar_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        webinar_uuid: typing.Union[MetaOapg.properties.webinar_uuid, str, schemas.Unset] = schemas.unset,
        start_time: typing.Union[MetaOapg.properties.start_time, str, datetime, schemas.Unset] = schemas.unset,
        survey_id: typing.Union[MetaOapg.properties.survey_id, str, schemas.Unset] = schemas.unset,
        survey_name: typing.Union[MetaOapg.properties.survey_name, str, schemas.Unset] = schemas.unset,
        survey_answers: typing.Union['ReportsGetWebinarSurveyReportResponseSurveyAnswers', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReportsGetWebinarSurveyReportResponse':
        return super().__new__(
            cls,
            *args,
            webinar_id=webinar_id,
            webinar_uuid=webinar_uuid,
            start_time=start_time,
            survey_id=survey_id,
            survey_name=survey_name,
            survey_answers=survey_answers,
            _configuration=_configuration,
            **kwargs,
        )

from zoom_meeting_python_sdk.model.reports_get_webinar_survey_report_response_survey_answers import ReportsGetWebinarSurveyReportResponseSurveyAnswers
