# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from zoom_meeting_python_sdk import schemas  # noqa: F401


class WebinarsGetSessionBrandingResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Information about the webinar's sessions branding.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def wallpaper() -> typing.Type['WebinarsGetSessionBrandingResponseWallpaper']:
                return WebinarsGetSessionBrandingResponseWallpaper
        
            @staticmethod
            def virtual_backgrounds() -> typing.Type['WebinarsGetSessionBrandingResponseVirtualBackgrounds']:
                return WebinarsGetSessionBrandingResponseVirtualBackgrounds
        
            @staticmethod
            def name_tags() -> typing.Type['WebinarsGetSessionBrandingResponseNameTags']:
                return WebinarsGetSessionBrandingResponseNameTags
            __annotations__ = {
                "wallpaper": wallpaper,
                "virtual_backgrounds": virtual_backgrounds,
                "name_tags": name_tags,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["wallpaper"]) -> 'WebinarsGetSessionBrandingResponseWallpaper': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["virtual_backgrounds"]) -> 'WebinarsGetSessionBrandingResponseVirtualBackgrounds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name_tags"]) -> 'WebinarsGetSessionBrandingResponseNameTags': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["wallpaper", "virtual_backgrounds", "name_tags", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["wallpaper"]) -> typing.Union['WebinarsGetSessionBrandingResponseWallpaper', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["virtual_backgrounds"]) -> typing.Union['WebinarsGetSessionBrandingResponseVirtualBackgrounds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name_tags"]) -> typing.Union['WebinarsGetSessionBrandingResponseNameTags', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["wallpaper", "virtual_backgrounds", "name_tags", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        wallpaper: typing.Union['WebinarsGetSessionBrandingResponseWallpaper', schemas.Unset] = schemas.unset,
        virtual_backgrounds: typing.Union['WebinarsGetSessionBrandingResponseVirtualBackgrounds', schemas.Unset] = schemas.unset,
        name_tags: typing.Union['WebinarsGetSessionBrandingResponseNameTags', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WebinarsGetSessionBrandingResponse':
        return super().__new__(
            cls,
            *args,
            wallpaper=wallpaper,
            virtual_backgrounds=virtual_backgrounds,
            name_tags=name_tags,
            _configuration=_configuration,
            **kwargs,
        )

from zoom_meeting_python_sdk.model.webinars_get_session_branding_response_name_tags import WebinarsGetSessionBrandingResponseNameTags
from zoom_meeting_python_sdk.model.webinars_get_session_branding_response_virtual_backgrounds import WebinarsGetSessionBrandingResponseVirtualBackgrounds
from zoom_meeting_python_sdk.model.webinars_get_session_branding_response_wallpaper import WebinarsGetSessionBrandingResponseWallpaper
