# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from zoom_meeting_python_sdk.type.webinars_update_scheduled_webinar_request_recurrence import WebinarsUpdateScheduledWebinarRequestRecurrence
from zoom_meeting_python_sdk.type.webinars_update_scheduled_webinar_request_settings import WebinarsUpdateScheduledWebinarRequestSettings
from zoom_meeting_python_sdk.type.webinars_update_scheduled_webinar_request_tracking_fields import WebinarsUpdateScheduledWebinarRequestTrackingFields

class RequiredWebinarsUpdateScheduledWebinarRequest(TypedDict):
    pass

class OptionalWebinarsUpdateScheduledWebinarRequest(TypedDict, total=False):
    # Webinar description.
    agenda: str

    # Webinar duration, in minutes. Used for scheduled webinar only.
    duration: int

    # [Webinar passcode](https://support.zoom.us/hc/en-us/articles/360033559832-Meeting-and-webinar-passwords). By default, passcode may only contain the following characters: [a-z A-Z 0-9 @ - _ * !] and can have a maximum of 10 characters.  **Note:** If the account owner or the admin has configured [minimum passcode requirement settings](https://support.zoom.us/hc/en-us/articles/360033559832-Meeting-and-webinar-passwords#h_a427384b-e383-4f80-864d-794bf0a37604), the passcode value provided here must meet those requirements.         If the requirements are enabled, you can view those requirements by calling either the [**Get user settings**](https://developers.zoom.us) API or the [**Get account settings**](https://developers.zoom.us) API.   If **Require a passcode when scheduling new meetings** setting has been **enabled** **and** [locked](https://support.zoom.us/hc/en-us/articles/115005269866-Using-Tiered-Settings#locked) for the user, the passcode field will be autogenerated for the webinar in the response even if it is not provided in the API request.
    password: str

    # The user's email address or `userId` to schedule a webinar for.
    schedule_for: str

    recurrence: WebinarsUpdateScheduledWebinarRequestRecurrence

    settings: WebinarsUpdateScheduledWebinarRequestSettings

    # Webinar start time, in the format `yyyy-MM-dd'T'HH:mm:ss'Z'`. Should be in GMT time. In the format `yyyy-MM-dd'T'HH:mm:ss`. This should be in local time and the timezone should be specified. Only used for scheduled webinars and recurring webinars with a fixed time.
    start_time: datetime

    # The timezone to assign to the `start_time` value. This field is only used for scheduled or recurring webinars with a fixed time.  For a list of supported timezones and their formats, see our [timezone list](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#timezones).
    timezone: str

    # The webinar topic.
    topic: str

    tracking_fields: WebinarsUpdateScheduledWebinarRequestTrackingFields

    # Webinar types.   `5` - webinar.    `6` - Recurring webinar with no fixed time.    `9` - Recurring webinar with a fixed time.
    type: int

    # Whether to set the webinar simulive.
    is_simulive: bool

    # The previously recorded file's ID for `simulive`.
    record_file_id: str

class WebinarsUpdateScheduledWebinarRequest(RequiredWebinarsUpdateScheduledWebinarRequest, OptionalWebinarsUpdateScheduledWebinarRequest):
    pass
