# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom. 

    The version of the OpenAPI document: 2
    Created by: https://developer.zoom.us/
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from zoom_meeting_python_sdk.type.webinars_create_webinar_request_recurrence import WebinarsCreateWebinarRequestRecurrence
from zoom_meeting_python_sdk.type.webinars_create_webinar_request_settings import WebinarsCreateWebinarRequestSettings
from zoom_meeting_python_sdk.type.webinars_create_webinar_request_tracking_fields import WebinarsCreateWebinarRequestTrackingFields

class RequiredWebinarsCreateWebinarRequest(TypedDict):
    pass

class OptionalWebinarsCreateWebinarRequest(TypedDict, total=False):
    # Webinar description.
    agenda: str

    # Webinar duration in minutes. Used for scheduled webinars only.
    duration: int

    # Webinar passcode. Passcode may only contain the characters [a-z A-Z 0-9 @ - _ * !]. Maximum of 10 characters.  If **Require a passcode when scheduling new meetings** setting has been **enabled** **and** [locked](https://support.zoom.us/hc/en-us/articles/115005269866-Using-Tiered-Settings#locked) for the user, the passcode field will be autogenerated for the Webinar in the response even if it is not provided in the API request.     **Note:** If the account owner or the admin has configured [minimum passcode requirement settings](https://support.zoom.us/hc/en-us/articles/360033559832-Meeting-and-webinar-passwords#h_a427384b-e383-4f80-864d-794bf0a37604), the passcode value provided here must meet those requirements.         If the requirements are enabled, you can view those requirements by calling the [**Get account settings**](https://developers.zoom.us/docs/api/rest/reference/zoom-api/ma#operation/accountSettings) API.
    password: str

    recurrence: WebinarsCreateWebinarRequestRecurrence

    # The email address or user ID of the user to schedule a webinar for.
    schedule_for: str

    settings: WebinarsCreateWebinarRequestSettings

    # Webinar start time. We support two formats for `start_time` - local time and GMT.       To set time as GMT the format should be `yyyy-MM-dd`T`HH:mm:ssZ`.  To set time using a specific timezone, use `yyyy-MM-dd`T`HH:mm:ss` format and specify the timezone [ID](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#timezones) in the `timezone` field OR leave it blank and the timezone set on your Zoom account will be used. You can also set the time as UTC as the timezone field.  The `start_time` should only be used for scheduled and / or recurring webinars with fixed time.
    start_time: datetime

    # The webinar template ID to schedule a webinar using a [webinar template](https://support.zoom.us/hc/en-us/articles/115001079746-Webinar-Templates) or a [admin webinar template](https://support.zoom.us/hc/en-us/articles/8137753618957-Configuring-admin-webinar-templates). For a list of webinar templates, use the [**List webinar templates**](https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods#operation/listWebinarTemplates) API.
    template_id: str

    # The timezone to assign to the `start_time` value. This field is only used for scheduled or recurring webinars with a fixed time.  For a list of supported timezones and their formats, see our [timezone list](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#timezones).
    timezone: str

    # Webinar topic.
    topic: str

    tracking_fields: WebinarsCreateWebinarRequestTrackingFields

    # Webinar types.  `5` - Webinar.    `6` - Recurring webinar with no fixed time.    `9` - Recurring webinar with a fixed time.
    type: int

    # Whether to set the webinar simulive.
    is_simulive: bool

    # The previously recorded file's ID for `simulive`.
    record_file_id: str

class WebinarsCreateWebinarRequest(RequiredWebinarsCreateWebinarRequest, OptionalWebinarsCreateWebinarRequest):
    pass
